#Connect SQL Server.
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=Duanthuctap
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true

spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2018Dialect
spring.jpa.hibernate.ddl-auto = update

spring.mandatory-file-encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
